name: textlint

on:
  push:
    branches:
    - master
    - draft/**
  pull_request:
    branches:
    - master

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3

    # setup Node.js
    - name: Setup Node.js environment
      uses: actions/setup-node@v3
      with:
        node-version: 18

    # Run scripts
    - name: Install dependencies
      run: yarn install
    - name: linting markdown files
      run: yarn run lint
